name: Auto Deploy
on:
  push:
    branches: [main]

env:
  NODE_VERSION: '22.x'

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    steps:
      - uses: actions/checkout@v4
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
            
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: tuanitpro/bee_kqxs_service:latest